import type { CountryCode } from "./geolocation";

export interface Festival {
  id: string;
  nameEn: string;
  nameLocal: string;
  startMonth: number;
  startDay: number;
  endMonth: number;
  endDay: number;
  emoji: string;
  descEn: string;
  descLocal: string;
  greetingEn: string;
  greetingLocal: string;
  themeFrom: string;
  themeTo: string;
  priority: number;
  countries: CountryCode[];
}

const festivals: Festival[] = [
  {
    id: "new-year",
    nameEn: "New Year",
    nameLocal: "Naya Saal Mubarak",
    startMonth: 1, startDay: 1, endMonth: 1, endDay: 2,
    emoji: "🎉",
    descEn: "Start your new year with the smartest pharmacy system!",
    descLocal: "Naye saal ki shuruat smartest pharmacy system ke saath karein!",
    greetingEn: "Happy New Year!",
    greetingLocal: "Naya Saal Mubarak!",
    themeFrom: "from-yellow-500", themeTo: "to-orange-600",
    priority: 80,
    countries: ["PK", "AE", "US", "GB"],
  },
  {
    id: "shab-e-meraj",
    nameEn: "Shab-e-Meraj",
    nameLocal: "Shab-e-Meraj Mubarak",
    startMonth: 1, startDay: 17, endMonth: 1, endDay: 18,
    emoji: "✨",
    descEn: "A blessed night calls for blessed decisions — upgrade today!",
    descLocal: "Mubarak raat, mubarak faisla — aaj hi upgrade karein!",
    greetingEn: "Shab-e-Meraj Mubarak!",
    greetingLocal: "Shab-e-Meraj Mubarak!",
    themeFrom: "from-blue-600", themeTo: "to-indigo-700",
    priority: 85,
    countries: ["PK", "AE"],
  },
  {
    id: "shab-e-barat",
    nameEn: "Shab-e-Barat",
    nameLocal: "Shab-e-Barat Mubarak",
    startMonth: 2, startDay: 1, endMonth: 2, endDay: 2,
    emoji: "🌙",
    descEn: "Blessed night, blessed savings on your pharmacy system!",
    descLocal: "Mubarak raat, pharmacy system pe mubarak bachat!",
    greetingEn: "Shab-e-Barat Mubarak!",
    greetingLocal: "Shab-e-Barat Mubarak!",
    themeFrom: "from-indigo-600", themeTo: "to-purple-700",
    priority: 85,
    countries: ["PK", "AE"],
  },
  {
    id: "kashmir-day",
    nameEn: "Kashmir Solidarity Day",
    nameLocal: "Youm-e-Yakjehti Kashmir",
    startMonth: 2, startDay: 5, endMonth: 2, endDay: 5,
    emoji: "🤝",
    descEn: "Stand united — upgrade your pharmacy this Kashmir Day!",
    descLocal: "Mutahid rahein — Kashmir Day pe apni pharmacy upgrade karein!",
    greetingEn: "Kashmir Solidarity Day",
    greetingLocal: "Youm-e-Yakjehti Kashmir",
    themeFrom: "from-green-600", themeTo: "to-emerald-700",
    priority: 70,
    countries: ["PK"],
  },
  {
    id: "presidents-day",
    nameEn: "Presidents' Day",
    nameLocal: "Presidents' Day",
    startMonth: 2, startDay: 17, endMonth: 2, endDay: 17,
    emoji: "🇺🇸",
    descEn: "Presidents' Day special — upgrade your pharmacy today!",
    descLocal: "Presidents' Day special — upgrade your pharmacy today!",
    greetingEn: "Happy Presidents' Day!",
    greetingLocal: "Happy Presidents' Day!",
    themeFrom: "from-blue-700", themeTo: "to-red-600",
    priority: 70,
    countries: ["US"],
  },
  {
    id: "ramzan",
    nameEn: "Ramzan Mubarak",
    nameLocal: "Ramzan Mubarak",
    startMonth: 2, startDay: 18, endMonth: 3, endDay: 19,
    emoji: "🌙",
    descEn: "This Ramzan, bless your pharmacy with AI-powered efficiency!",
    descLocal: "Is Ramzan, apni pharmacy ko AI-powered efficiency se nawazein!",
    greetingEn: "Ramzan Mubarak!",
    greetingLocal: "Ramzan Mubarak!",
    themeFrom: "from-emerald-600", themeTo: "to-teal-700",
    priority: 50,
    countries: ["PK", "AE"],
  },
  {
    id: "shab-e-qadr",
    nameEn: "Shab-e-Qadr",
    nameLocal: "Shab-e-Qadr Mubarak",
    startMonth: 3, startDay: 14, endMonth: 3, endDay: 15,
    emoji: "🤲",
    descEn: "The Night of Power — make a powerful decision for your pharmacy!",
    descLocal: "Laylatul Qadr — apni pharmacy ke liye zabardast faisla karein!",
    greetingEn: "Shab-e-Qadr Mubarak!",
    greetingLocal: "Shab-e-Qadr Mubarak!",
    themeFrom: "from-violet-600", themeTo: "to-purple-800",
    priority: 95,
    countries: ["PK", "AE"],
  },
  {
    id: "eid-ul-fitr",
    nameEn: "Eid ul-Fitr",
    nameLocal: "Eid ul-Fitr Mubarak",
    startMonth: 3, startDay: 20, endMonth: 3, endDay: 23,
    emoji: "🎊",
    descEn: "Celebrate Eid with a gift for your business — 30% OFF!",
    descLocal: "Eid ka tohfa apne business ke liye — 30% OFF!",
    greetingEn: "Eid Mubarak!",
    greetingLocal: "Eid Mubarak!",
    themeFrom: "from-emerald-500", themeTo: "to-green-700",
    priority: 100,
    countries: ["PK", "AE"],
  },
  {
    id: "pakistan-day",
    nameEn: "Pakistan Day",
    nameLocal: "Youm-e-Pakistan",
    startMonth: 3, startDay: 23, endMonth: 3, endDay: 23,
    emoji: "🇵🇰",
    descEn: "Celebrate Pakistan Day — invest in Pakistan's smartest pharmacy tech!",
    descLocal: "Youm-e-Pakistan mubarak — Pakistan ki smartest pharmacy tech mein invest karein!",
    greetingEn: "Happy Pakistan Day!",
    greetingLocal: "Youm-e-Pakistan Mubarak!",
    themeFrom: "from-green-600", themeTo: "to-emerald-800",
    priority: 90,
    countries: ["PK"],
  },
  {
    id: "st-georges-day",
    nameEn: "St. George's Day",
    nameLocal: "St. George's Day",
    startMonth: 4, startDay: 23, endMonth: 4, endDay: 23,
    emoji: "🏴󠁧󠁢󠁥󠁮󠁧󠁿",
    descEn: "Celebrate England's patron saint — upgrade your pharmacy today!",
    descLocal: "Celebrate England's patron saint — upgrade your pharmacy today!",
    greetingEn: "Happy St. George's Day!",
    greetingLocal: "Happy St. George's Day!",
    themeFrom: "from-red-600", themeTo: "to-white",
    priority: 70,
    countries: ["GB"],
  },
  {
    id: "labour-day",
    nameEn: "Labour Day",
    nameLocal: "Youm-e-Mazdoor",
    startMonth: 5, startDay: 1, endMonth: 5, endDay: 1,
    emoji: "💪",
    descEn: "Honour your hard work — let AI handle the heavy lifting!",
    descLocal: "Apni mehnat ki izzat karein — AI ko bhari kaam karne dein!",
    greetingEn: "Happy Labour Day!",
    greetingLocal: "Youm-e-Mazdoor Mubarak!",
    themeFrom: "from-red-600", themeTo: "to-orange-600",
    priority: 70,
    countries: ["PK", "AE"],
  },
  {
    id: "memorial-day-us",
    nameEn: "Memorial Day",
    nameLocal: "Memorial Day",
    startMonth: 5, startDay: 26, endMonth: 5, endDay: 26,
    emoji: "🇺🇸",
    descEn: "Honor the brave — upgrade your pharmacy this Memorial Day!",
    descLocal: "Honor the brave — upgrade your pharmacy this Memorial Day!",
    greetingEn: "Happy Memorial Day!",
    greetingLocal: "Happy Memorial Day!",
    themeFrom: "from-blue-700", themeTo: "to-red-700",
    priority: 75,
    countries: ["US"],
  },
  {
    id: "eid-ul-adha",
    nameEn: "Eid ul-Adha",
    nameLocal: "Eid ul-Adha Mubarak",
    startMonth: 5, startDay: 27, endMonth: 5, endDay: 30,
    emoji: "🐄",
    descEn: "This Eid ul-Adha, sacrifice manual work — go AI-powered!",
    descLocal: "Is Eid ul-Adha, manual kaam qurban karein — AI-powered ho jaein!",
    greetingEn: "Eid ul-Adha Mubarak!",
    greetingLocal: "Eid ul-Adha Mubarak!",
    themeFrom: "from-teal-600", themeTo: "to-cyan-700",
    priority: 100,
    countries: ["PK", "AE"],
  },
  {
    id: "independence-day-us",
    nameEn: "Independence Day",
    nameLocal: "Independence Day",
    startMonth: 7, startDay: 4, endMonth: 7, endDay: 4,
    emoji: "🇺🇸",
    descEn: "Celebrate freedom — free your pharmacy from old systems!",
    descLocal: "Celebrate freedom — free your pharmacy from old systems!",
    greetingEn: "Happy 4th of July!",
    greetingLocal: "Happy 4th of July!",
    themeFrom: "from-blue-700", themeTo: "to-red-600",
    priority: 95,
    countries: ["US"],
  },
  {
    id: "independence-day-pk",
    nameEn: "Independence Day",
    nameLocal: "Youm-e-Azadi Mubarak",
    startMonth: 8, startDay: 14, endMonth: 8, endDay: 14,
    emoji: "🇵🇰",
    descEn: "Free your pharmacy from old systems this Independence Day!",
    descLocal: "Youm-e-Azadi pe apni pharmacy ko purane systems se azad karein!",
    greetingEn: "Happy Independence Day!",
    greetingLocal: "Youm-e-Azadi Mubarak!",
    themeFrom: "from-green-600", themeTo: "to-emerald-700",
    priority: 95,
    countries: ["PK"],
  },
  {
    id: "labor-day-us",
    nameEn: "Labor Day",
    nameLocal: "Labor Day",
    startMonth: 9, startDay: 1, endMonth: 9, endDay: 1,
    emoji: "⚒️",
    descEn: "Let AI do the heavy lifting — upgrade this Labor Day!",
    descLocal: "Let AI do the heavy lifting — upgrade this Labor Day!",
    greetingEn: "Happy Labor Day!",
    greetingLocal: "Happy Labor Day!",
    themeFrom: "from-blue-600", themeTo: "to-indigo-700",
    priority: 70,
    countries: ["US"],
  },
  {
    id: "eid-milad",
    nameEn: "Eid Milad-un-Nabi \uFDFA",
    nameLocal: "Eid Milad-un-Nabi \uFDFA Mubarak",
    startMonth: 9, startDay: 5, endMonth: 9, endDay: 6,
    emoji: "🕌",
    descEn: "Celebrate the blessed day with blessings for your business!",
    descLocal: "Mubarak din ko apne business ke liye barkat ka zariya banaein!",
    greetingEn: "Eid Milad-un-Nabi Mubarak!",
    greetingLocal: "Eid Milad-un-Nabi \uFDFA Mubarak!",
    themeFrom: "from-green-700", themeTo: "to-emerald-800",
    priority: 90,
    countries: ["PK", "AE"],
  },
  {
    id: "defence-day",
    nameEn: "Defence Day",
    nameLocal: "Youm-e-Difa",
    startMonth: 9, startDay: 6, endMonth: 9, endDay: 6,
    emoji: "🎖️",
    descEn: "Defend your pharmacy profits with AI-powered management!",
    descLocal: "AI-powered management se apni pharmacy ke munafe ki hifazat karein!",
    greetingEn: "Happy Defence Day!",
    greetingLocal: "Youm-e-Difa Mubarak!",
    themeFrom: "from-green-700", themeTo: "to-teal-800",
    priority: 75,
    countries: ["PK"],
  },
  {
    id: "guy-fawkes",
    nameEn: "Guy Fawkes Night",
    nameLocal: "Bonfire Night",
    startMonth: 11, startDay: 5, endMonth: 11, endDay: 5,
    emoji: "🎆",
    descEn: "Light up your pharmacy with AI-powered automation!",
    descLocal: "Light up your pharmacy with AI-powered automation!",
    greetingEn: "Happy Bonfire Night!",
    greetingLocal: "Happy Bonfire Night!",
    themeFrom: "from-orange-600", themeTo: "to-red-700",
    priority: 70,
    countries: ["GB"],
  },
  {
    id: "iqbal-day",
    nameEn: "Iqbal Day",
    nameLocal: "Youm-e-Iqbal",
    startMonth: 11, startDay: 9, endMonth: 11, endDay: 9,
    emoji: "📖",
    descEn: "Dream big like Iqbal — modernize your pharmacy today!",
    descLocal: "Iqbal ki tarah khwab dekhein — aaj hi apni pharmacy modern karein!",
    greetingEn: "Happy Iqbal Day!",
    greetingLocal: "Youm-e-Iqbal Mubarak!",
    themeFrom: "from-amber-600", themeTo: "to-orange-700",
    priority: 75,
    countries: ["PK"],
  },
  {
    id: "thanksgiving-us",
    nameEn: "Thanksgiving",
    nameLocal: "Thanksgiving",
    startMonth: 11, startDay: 27, endMonth: 11, endDay: 27,
    emoji: "🦃",
    descEn: "Be thankful for smarter pharmacy management — upgrade today!",
    descLocal: "Be thankful for smarter pharmacy management — upgrade today!",
    greetingEn: "Happy Thanksgiving!",
    greetingLocal: "Happy Thanksgiving!",
    themeFrom: "from-orange-600", themeTo: "to-amber-700",
    priority: 85,
    countries: ["US"],
  },
  {
    id: "uae-national-day",
    nameEn: "UAE National Day",
    nameLocal: "اليوم الوطني الإماراتي",
    startMonth: 12, startDay: 2, endMonth: 12, endDay: 3,
    emoji: "🇦🇪",
    descEn: "Celebrate UAE National Day — invest in the smartest pharmacy tech!",
    descLocal: "احتفلوا باليوم الوطني — استثمروا في أذكى نظام صيدلية!",
    greetingEn: "Happy UAE National Day!",
    greetingLocal: "يوم وطني سعيد!",
    themeFrom: "from-red-600", themeTo: "to-green-700",
    priority: 95,
    countries: ["AE"],
  },
  {
    id: "christmas",
    nameEn: "Christmas",
    nameLocal: "Christmas",
    startMonth: 12, startDay: 25, endMonth: 12, endDay: 26,
    emoji: "🎄",
    descEn: "Merry Christmas — gift your pharmacy the smartest system!",
    descLocal: "Merry Christmas — gift your pharmacy the smartest system!",
    greetingEn: "Merry Christmas!",
    greetingLocal: "Merry Christmas!",
    themeFrom: "from-red-600", themeTo: "to-green-700",
    priority: 90,
    countries: ["US", "GB"],
  },
  {
    id: "quaid-day",
    nameEn: "Quaid-e-Azam Day",
    nameLocal: "Youm-e-Quaid",
    startMonth: 12, startDay: 25, endMonth: 12, endDay: 25,
    emoji: "⭐",
    descEn: "Follow the Quaid's vision — lead your pharmacy into the future!",
    descLocal: "Quaid ka khwab — apni pharmacy ko mustaqbil mein le jaein!",
    greetingEn: "Happy Quaid-e-Azam Day!",
    greetingLocal: "Youm-e-Quaid Mubarak!",
    themeFrom: "from-green-600", themeTo: "to-emerald-700",
    priority: 85,
    countries: ["PK"],
  },
];

function isDateInRange(month: number, day: number, f: Festival): boolean {
  if (f.startMonth === f.endMonth) {
    return month === f.startMonth && day >= f.startDay && day <= f.endDay;
  }
  const afterStart = month > f.startMonth || (month === f.startMonth && day >= f.startDay);
  const beforeEnd = month < f.endMonth || (month === f.endMonth && day <= f.endDay);
  return afterStart && beforeEnd;
}

export function getActiveFestival(countryCode: string = "PK"): Festival | null {
  const now = new Date();
  const month = now.getMonth() + 1;
  const day = now.getDate();

  const active = festivals.filter(
    (f) => f.countries.includes(countryCode as CountryCode) && isDateInRange(month, day, f)
  );
  if (active.length === 0) return null;
  active.sort((a, b) => b.priority - a.priority);
  return active[0];
}
