import { createContext, useContext, useState, useEffect, type ReactNode } from "react";

export type Lang = "en" | "ur" | "ar";

interface LanguageContextType {
  lang: Lang;
  setLang: (lang: Lang) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | null>(null);

export function useLanguage() {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error("useLanguage must be used within LanguageProvider");
  return ctx;
}

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [lang, setLangState] = useState<Lang>(() => {
    if (typeof window !== "undefined") {
      return (localStorage.getItem("lang") as Lang) || "en";
    }
    return "en";
  });

  const setLang = (l: Lang) => {
    setLangState(l);
    localStorage.setItem("lang", l);
  };

  const t = (key: string): string => {
    const val = translations[lang]?.[key];
    if (!val) return translations["en"]?.[key] || key;
    return val;
  };

  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

const translations: Record<Lang, Record<string, string>> = {
  en: {
    "nav.subtitle": "AI Powered Pharmacy System",
    "nav.features": "Features",
    "nav.pricing": "Pricing",
    "nav.demo": "Video Demo",
    "nav.faq": "FAQ",
    "nav.contact": "Contact",
    "nav.bookDemo": "Book Free Demo",

    "hero.badge": "AI-Powered Cloud Pharmacy System",
    "hero.title1": "Manage Your Pharmacy",
    "hero.title2": "Smarter with AI",
    "hero.subtitle": "Complete Cloud-Based Pharmacy Management System with POS, Smart Inventory, WhatsApp Automation & Real-Time Business Insights",
    "hero.bookDemo": "Book Free Demo on WhatsApp",
    "hero.watchDemo": "Pricing Plans",
    "hero.freeTraining": "Free Training",
    "hero.freeSupport": "Free Lifetime Support",
    "hero.worksOnMobile": "Works on Mobile & Desktop",
    "hero.secureCloud": "Secure Cloud System",
    "hero.ourClients": "Trusted by Pharmacies Across Pakistan",
    "hero.clientsPharmacies": "Pharmacies",
    "hero.clientsCities": "Cities",
    "hero.clientsSatisfaction": "Satisfaction",

    "video.title1": "See How It Works",
    "video.title2": "in Real Time",
    "video.subtitle": "Watch how billing, inventory, AI insights and WhatsApp automation work live.",
    "video.bookDemo": "Book Free Demo Now",

    "problem.badge": "The Problem",
    "problem.title1": "Still Managing Your Pharmacy",
    "problem.title2": "the Old Way?",
    "problem.subtitle": "These problems are silently draining your pharmacy's profit every single day — and most owners don't even realize it.",
    "problem.1.title": "Slow Manual Billing",
    "problem.1.text": "Long queues, slow service — customers leave frustrated while you're stuck with paper registers.",
    "problem.1.stat": "3x slower",
    "problem.2.title": "Expired Stock Losses",
    "problem.2.text": "Without tracking, expired medicines sit on shelves costing you real money every single day.",
    "problem.2.stat": "Rs 50K+ lost/yr",
    "problem.3.title": "Zero Inventory Control",
    "problem.3.text": "You never know what's in stock, what's running low, or when to reorder. Complete guesswork.",
    "problem.3.stat": "30% waste",
    "problem.4.title": "Staff Issues",
    "problem.4.text": "No way to track who sold what, monitor performance, or control who accesses your data.",
    "problem.4.stat": "No visibility",
    "problem.5.title": "Losing Customers Daily",
    "problem.5.text": "No follow-ups, no medicine reminders — your customers forget about you and go to competitors.",
    "problem.5.stat": "40% churn",
    "problem.6.title": "No Growth Insights",
    "problem.6.text": "Without analytics, you're guessing instead of making smart, data-driven business decisions.",
    "problem.6.stat": "Flying blind",
    "problem.cta1": "Stop losing money.",
    "problem.cta2": "It's time to upgrade.",
    "problem.ctaButton": "Upgrade Now",

    "solution.badge": "Powerful Features",
    "solution.title1": "All-in-One AI Pharmacy",
    "solution.title2": "Management System",
    "solution.subtitle": "Everything you need to run a modern, profitable pharmacy — powered by artificial intelligence.",
    "solution.f1.title": "Lightning Fast POS Billing",
    "solution.f1.desc": "Bill customers in seconds with smart search & auto-calculations.",
    "solution.f2.title": "Real-Time Inventory Tracking",
    "solution.f2.desc": "Know your stock levels, expiry dates, and reorder points instantly.",
    "solution.f3.title": "Expiry Alerts & Notifications",
    "solution.f3.desc": "Never lose money on expired stock with automatic alerts.",
    "solution.f4.title": "Reports & Profit Dashboard",
    "solution.f4.desc": "Track revenue, expenses, and profits with visual dashboards.",
    "solution.f5.title": "Staff Management System",
    "solution.f5.desc": "Control access, roles, and monitor staff activity in real-time.",
    "solution.f6.title": "WhatsApp Marketing",
    "solution.f6.desc": "Send offers, reminders, and follow-ups directly via WhatsApp.",
    "solution.f7.title": "AI Sales Insights",
    "solution.f7.desc": "Get AI-powered suggestions to boost sales and reduce waste.",
    "solution.f8.title": "Cloud Access Anywhere",
    "solution.f8.desc": "Access your pharmacy data securely from any device, anywhere.",
    "solution.f9.title": "Secure Data Protection",
    "solution.f9.desc": "SSL encryption, daily backups, and enterprise-grade security.",
    "solution.f10.title": "Business Growth Analytics",
    "solution.f10.desc": "Track growth trends and identify opportunities to scale.",
    "solution.aiPowered": "AI POWERED",
    "solution.ctaButton": "Get All Features",

    "whatsapp.badge": "WhatsApp Automation (No API Required)",
    "whatsapp.title": "Built-In WhatsApp Marketing",
    "whatsapp.subtitle": "Automatically engage customers with personalized messages — without APIs, integrations, or extra tools.",
    "whatsapp.desc": "Increase retention, automate reminders, and boost repeat purchases effortlessly. Everything runs inside your pharmacy system with zero setup.",
    "whatsapp.benefitsTitle": "Benefits",
    "whatsapp.b1": "Increase Revenue",
    "whatsapp.b2": "More Repeat Sales",
    "whatsapp.b3": "Instant Comms",
    "whatsapp.b4": "No Extra Tools",
    "whatsapp.ctaButton": "Start Automating Today",
    "whatsapp.float1": "Discount Offers",
    "whatsapp.float2": "Reminders",
    "whatsapp.float3": "Thank You",
    "whatsapp.float4": "Follow-ups",
    "whatsapp.f1desc": "Auto-send special deals & flash sales directly to customer WhatsApp.",
    "whatsapp.f2desc": "Automated medicine refill & appointment reminders sent on time, every time.",
    "whatsapp.f3desc": "Instant thank-you messages after every purchase to build loyalty.",
    "whatsapp.f4desc": "Smart follow-ups to bring back inactive customers automatically.",
    "whatsapp.stat1": "More Repeat Sales",
    "whatsapp.stat2": "Message Open Rate",
    "whatsapp.stat3": "No API Needed",
    "whatsapp.noApiNote": "No third-party API or extra subscription needed — works out of the box.",

    "owner.badge": "Owner Dashboard",
    "owner.title1": "Total Business Control.",
    "owner.title2": "One Owner Login.",
    "owner.subtitle": "Manage staff, track revenue, monitor inventory, analyze performance, and control your entire pharmacy — all from one secure owner login or mobile app.",
    "owner.f1": "Staff Management",
    "owner.f1.desc": "Add, remove, and control staff access with role-based permissions.",
    "owner.f2": "Salary Management",
    "owner.f2.desc": "Track payroll, monthly payments, and salary history at a glance.",
    "owner.f3": "Profit & Revenue",
    "owner.f3.desc": "Monitor income, expenses, and business growth with live charts.",
    "owner.f4": "AI Insights",
    "owner.f4.desc": "Get smart suggestions powered by AI to improve your performance.",
    "owner.f5": "Supplier Management",
    "owner.f5.desc": "Track vendors, purchase records, and delivery statuses.",
    "owner.f6": "Reports & Analytics",
    "owner.f6.desc": "View and download detailed performance reports instantly.",
    "owner.f7": "AI Inventory Control",
    "owner.f7.desc": "Automatic stock alerts and smart restocking recommendations.",
    "owner.f8": "Secure Owner Login",
    "owner.f8.desc": "Full control with encrypted, secure owner-only access.",
    "owner.f9": "Mobile App Control",
    "owner.f9.desc": "Manage your entire business from anywhere, on any device.",
    "owner.ctaButton": "Access Owner Dashboard",
    "owner.ctaSubtext": "Complete control. Zero complexity.",

    "comparison.title1": "Why Upgrade to",
    "comparison.title2": "AI Pharmacy System?",
    "comparison.subtitle": "See how our AI-powered system outperforms manual processes and outdated software in every critical area of pharmacy management.",
    "comparison.feature": "Feature",
    "comparison.manual": "Manual",
    "comparison.oldSoftware": "Old Software",
    "comparison.ourSystem": "Our AI System",
    "comparison.r1": "Billing Speed",
    "comparison.r1.desc": "Process prescriptions and generate invoices at lightning speed with smart auto-complete and barcode scanning.",
    "comparison.r1.manual": "Slow",
    "comparison.r1.old": "Medium",
    "comparison.r1.ai": "Instant",
    "comparison.r2": "Error Reduction",
    "comparison.r2.desc": "AI-powered validation catches dosage conflicts, duplicate entries, and pricing errors before they happen.",
    "comparison.r2.manual": "High Risk",
    "comparison.r2.old": "Medium Risk",
    "comparison.r2.ai": "Near Zero",
    "comparison.r3": "Inventory Tracking",
    "comparison.r3.desc": "Real-time stock monitoring with smart reorder points, low-stock alerts, and supplier integration.",
    "comparison.r3.manual": "No",
    "comparison.r3.old": "Limited",
    "comparison.r3.ai": "AI-Smart",
    "comparison.r4": "Expiry Management",
    "comparison.r4.desc": "Automatic alerts for expiring medicines with smart FEFO (First Expiry, First Out) suggestions and return tracking.",
    "comparison.r4.manual": "No",
    "comparison.r4.old": "No",
    "comparison.r4.ai": "Automated",
    "comparison.r5": "Business Automation",
    "comparison.r5.desc": "Automate repetitive tasks like purchase orders, WhatsApp marketing, customer reminders, and staff schedules.",
    "comparison.r5.manual": "None",
    "comparison.r5.old": "Basic",
    "comparison.r5.ai": "Full AI",
    "comparison.r6": "Reports & Analytics",
    "comparison.r6.desc": "Real-time dashboards with profit analysis, sales trends, staff performance, and AI-generated business insights.",
    "comparison.r6.manual": "None",
    "comparison.r6.old": "Basic",
    "comparison.r6.ai": "AI-Powered",
    "comparison.r7": "Profit Growth",
    "comparison.r7.desc": "Maximize revenue with smart pricing suggestions, dead stock identification, and data-driven purchasing decisions.",
    "comparison.r7.manual": "Low",
    "comparison.r7.old": "Medium",
    "comparison.r7.ai": "Up to +30%",
    "comparison.r8": "Remote Access",
    "comparison.r8.desc": "Monitor and manage your pharmacy from anywhere using cloud-based dashboard accessible on mobile, tablet, or desktop.",
    "comparison.r8.manual": "No",
    "comparison.r8.old": "No",
    "comparison.r8.ai": "Full Cloud",
    "comparison.r9": "Customer Retention",
    "comparison.r9.desc": "Build loyalty with automated WhatsApp follow-ups, prescription reminders, and personalized promotions.",
    "comparison.r9.manual": "No",
    "comparison.r9.old": "No",
    "comparison.r9.ai": "AI-Driven",
    "comparison.r10": "Data Security",
    "comparison.r10.desc": "Enterprise-grade encryption, automatic cloud backups, role-based access control, and complete audit trails.",
    "comparison.r10.manual": "None",
    "comparison.r10.old": "Basic",
    "comparison.r10.ai": "Enterprise",
    "comparison.r11": "Owner Control",
    "comparison.r11.desc": "Full owner dashboard with real-time monitoring, staff management, salary tracking, and complete business oversight from any device.",
    "comparison.r11.manual": "Limited",
    "comparison.r11.old": "Basic",
    "comparison.r11.ai": "Full Control",
    "comparison.r12": "Premium Support",
    "comparison.r12.desc": "Dedicated support team with priority WhatsApp assistance, remote troubleshooting, regular updates, and personalized onboarding training.",
    "comparison.r12.manual": "None",
    "comparison.r12.old": "Email Only",
    "comparison.r12.ai": "24/7 Priority",
    "comparison.ctaButton": "Upgrade to AI System",

    "pricing.limitedOffer": "Limited Time Offer",
    "pricing.offerEnds": "Offer Ends Soon",
    "pricing.missOut": "Don't miss out — Limited seats available!",
    "pricing.days": "Days",
    "pricing.hours": "Hours",
    "pricing.min": "Min",
    "pricing.sec": "Sec",
    "pricing.basic": "Starter",
    "pricing.standard": "Standard",
    "pricing.premium": "Premium",
    "pricing.oneTime": "One-time payment",
    "pricing.save": "Save",
    "pricing.starterNote": "Perfect for small pharmacies",
    "pricing.standardNote": "Best for growing pharmacies",
    "pricing.premiumNote": "For fully automated pharmacy businesses",
    "pricing.monthlyTitle": "Monthly Subscription Plans Available",
    "pricing.monthlySub": "Includes domain, hosting, database, system updates, and full support — all in one fixed monthly fee.",
    "pricing.startMonthly": "Contact Us For Monthly Plans",
    "pricing.investTitle": "One-Time Investment, Lifetime Value",
    "pricing.investSub": "Invest once and enjoy lifetime access, updates, and support.",
    "pricing.recommended": "Recommended",
    "pricing.mostPopular": "Most Popular",
    "pricing.getStarted": "Get Started",
    "pricing.upgradeStandard": "Upgrade to Standard",
    "pricing.getPremium": "Get Premium Now",
    "pricing.everythingBasicPlus": "Everything in Starter PLUS:",
    "pricing.everythingStandardPlus": "Everything in Standard PLUS:",
    "pricing.aiPowered": "AI Powered",
    "pricing.hosting": "Hosting & Domain",
    "pricing.hostingSub": "Hosting, Database & Domain cost separate — You Pay",
    "pricing.yourBrand": "Your Own Brand",
    "pricing.brandSub": "e.g. www.yourpharmacy.com",
    "pricing.fullSecurity": "Full Security",
    "pricing.securitySub": "SSL, encryption & daily backups",
    "pricing.f.pos": "POS Billing System",
    "pricing.f.inventory": "Smart Inventory Management",
    "pricing.f.expiry": "Expiry Alert System",
    "pricing.f.salesReports": "Sales Reports",
    "pricing.f.profitTracking": "Profit Tracking",
    "pricing.f.basicDashboard": "Basic Dashboard",
    "pricing.f.invoiceCustom": "Invoice Customization",
    "pricing.f.multiUserLimited": "Multi-User Access (Limited)",
    "pricing.f.dataBackup": "Data Backup System",
    "pricing.f.freeTrainingSetup": "Free Training & Setup",
    "pricing.f.advancedPos": "Advanced POS",
    "pricing.f.fullInventory": "Full Inventory Control",
    "pricing.f.advancedExpiry": "Advanced Expiry Alerts",
    "pricing.f.whatsappMarketing": "WhatsApp Marketing System",
    "pricing.f.staffMgmt": "Staff Management",
    "pricing.f.multiDevice": "Multi-Device Access",
    "pricing.f.advancedReports": "Advanced Reports",
    "pricing.f.profitAnalytics": "Profit Analytics",
    "pricing.f.customerHistory": "Customer History Tracking",
    "pricing.f.prioritySupport": "Priority Support",
    "pricing.f.aiSalesInsights": "AI Sales Insights",
    "pricing.f.aiMessageWriter": "AI Message Writer",
    "pricing.f.fullAutomation": "Full Business Automation",
    "pricing.f.cloudHosting": "Cloud Hosting Setup",
    "pricing.f.advancedDashboard": "Advanced Dashboard",
    "pricing.f.unlimitedStaff": "Unlimited Staff Accounts",
    "pricing.f.advancedSecurity": "Advanced Security",
    "pricing.f.performanceTracking": "Performance Tracking",
    "pricing.f.smartRestock": "Smart Restock Suggestions",
    "pricing.f.vipSupport": "VIP Priority Support",

    "roi.title1": "Grow Faster with",
    "roi.title2": "AI",
    "roi.s1.label": "Time Saved",
    "roi.s2.label": "Reduce Stock Loss",
    "roi.s3.label": "Increase Profit",
    "roi.s4.label": "Tasks Automated",

    "bonuses.badge": "Free Bonuses",
    "bonuses.title": "Get More Than Just Software",
    "bonuses.b1.title": "Free Complete Training",
    "bonuses.b1.desc": "Full hands-on training for you and your staff. Learn every feature step-by-step.",
    "bonuses.b2.title": "Free Lifetime Support",
    "bonuses.b2.desc": "Get expert help anytime via WhatsApp or call. We're always available for you.",
    "bonuses.b3.title": "Free Setup & Installation",
    "bonuses.b3.desc": "Our team handles full installation and configuration. You don't need any technical skills.",
    "bonuses.b4.title": "Free Data Migration",
    "bonuses.b4.desc": "Using Abuzar or other software? We export your old data and import it safely.",
    "bonuses.b5.title": "Free Updates",
    "bonuses.b5.desc": "System upgrades without extra charges. Stay modern and competitive with latest tech.",
    "bonuses.b6.title": "Free Security Setup",
    "bonuses.b6.desc": "Complete data protection with backup system. Your pharmacy data stays safe and secure.",

    "testimonials.badge": "Real Reviews",
    "testimonials.title1": "What Our Customers",
    "testimonials.title2": "Say",
    "testimonials.subtitle": "Trusted by pharmacy owners across Pakistan",

    "demo.title1": "See It Live",
    "demo.title2": "Book Your Free Demo",
    "demo.ctaButton": "Chat on WhatsApp",
    "demo.prefilled": 'Prefilled: "Hi, I want demo of AI Pharmacy System."',

    "faq.title1": "Frequently Asked",
    "faq.title2": "Questions",
    "faq.q1": "Does it work on mobile?",
    "faq.a1": "Yes! Our system works on all mobile phones, tablets, and desktop computers. Access it from any browser, anywhere.",
    "faq.q2": "Will I get training?",
    "faq.a2": "Yes - completely free! Full onboarding and step-by-step training included for you and your entire staff.",
    "faq.q3": "Is my data secure?",
    "faq.a3": "Fully Secure. Industry-standard encryption, daily backups, and only authorized access. Your data is safe with us.",
    "faq.q4": "Does it work on multiple devices?",
    "faq.a4": "Yes! Standard and Premium plans support multi-device access. Basic plan includes limited multi-user access.",
    "faq.q5": "Can I import my old data?",
    "faq.a5": "Absolutely! If you're using Abuzar or any other old software, we safely export your data and import it into the new system. No data loss.",
    "faq.q6": "What if there's no internet?",
    "faq.a6": "The system is cloud-based, but basic billing works offline too. When internet comes back, data automatically syncs. Premium plan includes full offline support.",
    "faq.q7": "How long does setup take?",
    "faq.a7": "Setup completes in 24-48 hours. Our team handles full installation, configuration, and training. You don't need any technical knowledge.",

    "showcase.badge": "See It In Action",
    "showcase.title": "Everything Your Pharmacy Needs, In One System",
    "showcase.subtitle": "From billing to AI insights — manage your entire pharmacy with one powerful, easy-to-use platform built for Pakistani pharmacies.",
    "showcase.cta": "Book Free Demo",
    "showcase.check1": "Free Setup",
    "showcase.check2": "24/7 Support",

    "footer.smartPharmacy": "Start Your Smart Pharmacy Today.",
    "footer.chatWithUs": "Chat with Us",
    "footer.quickLinks": "Quick Links",
    "footer.contact": "Contact",
    "footer.whatsapp": "WhatsApp",
    "footer.copyright": "2026 Anas Tech Services. All rights reserved.",

    "chatbot.title": "AI Pharmacy Assistant",
    "chatbot.status": "Online • Pricing • Features • Advice",
    "chatbot.welcome": "Assalam o Alaikum! 👋 I'm your AI assistant for Anas Tech Services Pharmacy System. Ask me about pricing, features, comparisons, or anything else!",
    "chatbot.askQuestions": "Ask Questions?",
    "chatbot.askAI": "Ask AI",
    "chatbot.placeholder": "Ask about pricing, features, advice...",
    "chatbot.powered": "Powered by",
    "chatbot.q1": "Compare pricing plans",
    "chatbot.q2": "What features do I get?",
    "chatbot.q3": "Why choose this over manual?",
    "chatbot.q4": "Is there a mobile app?",
    "chatbot.q5": "Tell me about bonuses",
    "chatbot.error": "Sorry, I'm having trouble connecting. Please try again.",
    "chatbot.newChat": "New Chat",
    "chatbot.minimize": "Minimize",
    "chatbot.fullscreen": "Fullscreen",
    "chatbot.close": "Close",
  },

  ur: {
    "nav.subtitle": "AI Pharmacy System",
    "nav.features": "Features",
    "nav.pricing": "Qeemat",
    "nav.demo": "Video Demo",
    "nav.faq": "Sawalaat",
    "nav.contact": "Rabta",
    "nav.bookDemo": "Free Demo Book Karein",

    "hero.badge": "AI-Powered Cloud Pharmacy System",
    "hero.title1": "Apni Pharmacy Chalayein",
    "hero.title2": "AI ke Saath Smart Tareeqe Se",
    "hero.subtitle": "Mukammal Cloud-Based Pharmacy Management System — POS, Smart Inventory, WhatsApp Automation aur Real-Time Business Insights ke saath",
    "hero.bookDemo": "WhatsApp pe Free Demo Book Karein",
    "hero.watchDemo": "Qeemat Dekhein",
    "hero.freeTraining": "Free Training",
    "hero.freeSupport": "Free Lifetime Support",
    "hero.worksOnMobile": "Mobile aur Desktop pe Chalta Hai",
    "hero.secureCloud": "Secure Cloud System",
    "hero.ourClients": "Pakistan Bhar Ki Pharmacies Ka Bharosa",
    "hero.clientsPharmacies": "Pharmacies",
    "hero.clientsCities": "Sheher",
    "hero.clientsSatisfaction": "Tasalli",

    "video.title1": "Dekhein Ye Kaise",
    "video.title2": "Kaam Karta Hai",
    "video.subtitle": "Dekhein billing, inventory, AI insights aur WhatsApp automation kaise kaam karta hai.",
    "video.bookDemo": "Abhi Free Demo Book Karein",

    "problem.badge": "Masla Kya Hai",
    "problem.title1": "Abhi Bhi Pharmacy Chalate Ho",
    "problem.title2": "Purane Tareeqe Se?",
    "problem.subtitle": "Ye maslay har roz apki pharmacy ka munafa chupke se kha rahe hain — aur zyada tar maalikon ko pata bhi nahi chalta.",
    "problem.1.title": "Dheemi Manual Billing",
    "problem.1.text": "Lambi qataarein, dheemi service — customer pareshan ho ke chale jaate hain aur aap kaghaz ke register mein phansey ho.",
    "problem.1.stat": "3x dheema",
    "problem.2.title": "Expired Stock ka Nuqsaan",
    "problem.2.text": "Tracking ke baghair, expired dawaiyan shelves pe pari rehti hain aur har roz paisa zaaya hota hai.",
    "problem.2.stat": "Rs 50K+ nuqsaan/saal",
    "problem.3.title": "Inventory ka Koi Control Nahi",
    "problem.3.text": "Pata hi nahi chalta kya stock mein hai, kya khatam ho raha hai, ya kab reorder karna hai. Bas andaza lagao.",
    "problem.3.stat": "30% barbadi",
    "problem.4.title": "Staff ke Masail",
    "problem.4.text": "Kis ne kya becha, performance kaisi hai, data kis ke paas hai — kuch pata nahi chalta.",
    "problem.4.stat": "Koi nazar nahi",
    "problem.5.title": "Customers Roz Ja Rahe Hain",
    "problem.5.text": "Na follow-up, na dawai ki yaad-dehani — customer bhool jaate hain aur competitor ke paas chale jaate hain.",
    "problem.5.stat": "40% customers gaye",
    "problem.6.title": "Growth ki Samajh Nahi",
    "problem.6.text": "Analytics ke baghair, aap andaze se kaam kar rahe ho — smart, data-driven faislay nahi le sakte.",
    "problem.6.stat": "Andha kaam",
    "problem.cta1": "Paisa zaaya karna band karein.",
    "problem.cta2": "Ab upgrade ka waqt hai.",
    "problem.ctaButton": "Abhi Upgrade Karein",

    "solution.badge": "Zabardast Features",
    "solution.title1": "All-in-One AI Pharmacy",
    "solution.title2": "Management System",
    "solution.subtitle": "Ek modern, munafa-mand pharmacy chalane ke liye sab kuch — AI ki taaqat ke saath.",
    "solution.f1.title": "Tez Tareen POS Billing",
    "solution.f1.desc": "Smart search aur auto-calculations se secondon mein bill banayein.",
    "solution.f2.title": "Real-Time Inventory Tracking",
    "solution.f2.desc": "Stock levels, expiry dates, aur reorder points foran dekhein.",
    "solution.f3.title": "Expiry Alerts aur Notifications",
    "solution.f3.desc": "Automatic alerts se expired stock pe kabhi paisa zaaya nahi hoga.",
    "solution.f4.title": "Reports aur Profit Dashboard",
    "solution.f4.desc": "Revenue, expenses, aur munafe ko visual dashboards se track karein.",
    "solution.f5.title": "Staff Management System",
    "solution.f5.desc": "Access control karein, roles set karein, aur staff activity real-time dekhein.",
    "solution.f6.title": "WhatsApp Marketing",
    "solution.f6.desc": "WhatsApp ke zariye offers, yaad-dehani, aur follow-ups bhejein.",
    "solution.f7.title": "AI Sales Insights",
    "solution.f7.desc": "AI ki madad se sales badhayein aur waste kam karein.",
    "solution.f8.title": "Cloud Access Kahin Se Bhi",
    "solution.f8.desc": "Kisi bhi device se kahin se bhi apna pharmacy data access karein.",
    "solution.f9.title": "Secure Data Protection",
    "solution.f9.desc": "SSL encryption, daily backups, aur enterprise-grade security.",
    "solution.f10.title": "Business Growth Analytics",
    "solution.f10.desc": "Growth trends track karein aur scale karne ke mauqe dhundhein.",
    "solution.aiPowered": "AI POWERED",
    "solution.ctaButton": "Saare Features Lein",

    "whatsapp.badge": "WhatsApp Automation (Koi API Nahi Chahiye)",
    "whatsapp.title": "Built-In WhatsApp Marketing",
    "whatsapp.subtitle": "Customers ko personalized messages se khud ba khud engage karein — bina APIs, integrations, ya extra tools ke.",
    "whatsapp.desc": "Retention badhayein, reminders automate karein, aur repeat purchases asani se badhayein. Sab kuch apke pharmacy system ke andar chalta hai bina kisi setup ke.",
    "whatsapp.benefitsTitle": "Faide",
    "whatsapp.b1": "Revenue Badhayein",
    "whatsapp.b2": "Zyada Repeat Sales",
    "whatsapp.b3": "Fori Communication",
    "whatsapp.b4": "Koi Extra Tool Nahi",
    "whatsapp.ctaButton": "Aaj Hi Automate Karein",
    "whatsapp.float1": "Discount Offers",
    "whatsapp.float2": "Yaad-dehani",
    "whatsapp.float3": "Shukriya",
    "whatsapp.float4": "Follow-ups",
    "whatsapp.f1desc": "Customers ko special deals aur flash sales seedha WhatsApp pe bhejtay hain.",
    "whatsapp.f2desc": "Medicine refill aur appointment ke automatic reminders waqt par bhejtay hain.",
    "whatsapp.f3desc": "Har khareedari ke baad fori shukriya message se loyalty banayein.",
    "whatsapp.f4desc": "Inactive customers ko dobara laane ke liye smart follow-ups khud ba khud chalte hain.",
    "whatsapp.stat1": "Zyada Repeat Sales",
    "whatsapp.stat2": "Message Open Rate",
    "whatsapp.stat3": "Koi API Nahi",
    "whatsapp.noApiNote": "Koi third-party API ya extra subscription nahi — system ke andar se hi chalta hai.",

    "owner.badge": "Owner Dashboard",
    "owner.title1": "Mukammal Business Control.",
    "owner.title2": "Ek Owner Login.",
    "owner.subtitle": "Staff manage karein, revenue track karein, inventory monitor karein, performance analyze karein — sab ek secure owner login ya mobile app se.",
    "owner.f1": "Staff Management",
    "owner.f1.desc": "Staff ko add, remove karein aur role-based permissions se access control karein.",
    "owner.f2": "Salary Management",
    "owner.f2.desc": "Payroll, monthly payments, aur salary ki taareekh ek nazar mein dekhein.",
    "owner.f3": "Munafa aur Revenue",
    "owner.f3.desc": "Income, expenses, aur business growth live charts se monitor karein.",
    "owner.f4": "AI Insights",
    "owner.f4.desc": "AI ki madad se smart suggestions lein performance behtar karne ke liye.",
    "owner.f5": "Supplier Management",
    "owner.f5.desc": "Vendors, purchase records, aur delivery statuses track karein.",
    "owner.f6": "Reports aur Analytics",
    "owner.f6.desc": "Detailed performance reports foran dekhein aur download karein.",
    "owner.f7": "AI Inventory Control",
    "owner.f7.desc": "Automatic stock alerts aur smart restocking ki recommendations.",
    "owner.f8": "Secure Owner Login",
    "owner.f8.desc": "Encrypted, secure owner-only access ke saath mukammal control.",
    "owner.f9": "Mobile App Control",
    "owner.f9.desc": "Kahin se bhi, kisi bhi device pe apna poora business manage karein.",
    "owner.ctaButton": "Owner Dashboard Access Karein",
    "owner.ctaSubtext": "Mukammal control. Aasaan tareeqa.",

    "comparison.title1": "Kyun Upgrade Karein",
    "comparison.title2": "AI Pharmacy System?",
    "comparison.subtitle": "Dekhein kaise hamara AI system manual kaam aur purane software se har important pharmacy kaam mein behtar hai.",
    "comparison.feature": "Feature",
    "comparison.manual": "Manual",
    "comparison.oldSoftware": "Purana Software",
    "comparison.ourSystem": "Hamara AI System",
    "comparison.r1": "Billing Speed",
    "comparison.r1.desc": "Smart auto-complete aur barcode scanning se prescriptions aur invoices fori tayyar karein.",
    "comparison.r1.manual": "Dheemi",
    "comparison.r1.old": "Theek Thaak",
    "comparison.r1.ai": "Fori",
    "comparison.r2": "Ghaltiyon mein Kami",
    "comparison.r2.desc": "AI dosage conflicts, duplicate entries aur pricing ghaltiyan hone se pehle pakad leta hai.",
    "comparison.r2.manual": "Zyada Khatra",
    "comparison.r2.old": "Darmiyana Khatra",
    "comparison.r2.ai": "Na ke Barabar",
    "comparison.r3": "Inventory Tracking",
    "comparison.r3.desc": "Real-time stock monitoring, smart reorder points, low-stock alerts aur supplier integration.",
    "comparison.r3.manual": "Nahi",
    "comparison.r3.old": "Mehduud",
    "comparison.r3.ai": "AI-Smart",
    "comparison.r4": "Expiry Management",
    "comparison.r4.desc": "Expire hone wali dawaiyon ka automatic alert, FEFO suggestions aur return tracking.",
    "comparison.r4.manual": "Nahi",
    "comparison.r4.old": "Nahi",
    "comparison.r4.ai": "Automatic",
    "comparison.r5": "Business Automation",
    "comparison.r5.desc": "Purchase orders, WhatsApp marketing, customer reminders aur staff schedules khud ba khud chalein.",
    "comparison.r5.manual": "Koi Nahi",
    "comparison.r5.old": "Basic",
    "comparison.r5.ai": "Mukammal AI",
    "comparison.r6": "Reports & Analytics",
    "comparison.r6.desc": "Real-time dashboards, munafa analysis, sales trends, staff performance aur AI insights.",
    "comparison.r6.manual": "Nahi",
    "comparison.r6.old": "Basic",
    "comparison.r6.ai": "AI-Powered",
    "comparison.r7": "Munafe ki Growth",
    "comparison.r7.desc": "Smart pricing, dead stock ki pehchan aur data-based purchasing se revenue barhaein.",
    "comparison.r7.manual": "Kam",
    "comparison.r7.old": "Darmiyan",
    "comparison.r7.ai": "+30% Tak",
    "comparison.r8": "Remote Access",
    "comparison.r8.desc": "Cloud-based dashboard se pharmacy kahin se bhi mobile, tablet ya desktop pe manage karein.",
    "comparison.r8.manual": "Nahi",
    "comparison.r8.old": "Nahi",
    "comparison.r8.ai": "Full Cloud",
    "comparison.r9": "Customer Retention",
    "comparison.r9.desc": "Automatic WhatsApp follow-ups, prescription reminders aur personalized promotions se customers waapas aayein.",
    "comparison.r9.manual": "Nahi",
    "comparison.r9.old": "Nahi",
    "comparison.r9.ai": "AI-Driven",
    "comparison.r10": "Data Security",
    "comparison.r10.desc": "Enterprise encryption, automatic cloud backups, role-based access aur complete audit trails.",
    "comparison.r10.manual": "Nahi",
    "comparison.r10.old": "Basic",
    "comparison.r10.ai": "Enterprise",
    "comparison.r11": "Owner Control",
    "comparison.r11.desc": "Real-time monitoring, staff management, salary tracking aur complete business oversight kisi bhi device se.",
    "comparison.r11.manual": "Mehduud",
    "comparison.r11.old": "Basic",
    "comparison.r11.ai": "Mukammal Control",
    "comparison.r12": "Premium Support",
    "comparison.r12.desc": "Dedicated support team, priority WhatsApp madad, remote troubleshooting, regular updates aur training.",
    "comparison.r12.manual": "Nahi",
    "comparison.r12.old": "Sirf Email",
    "comparison.r12.ai": "24/7 Priority",
    "comparison.ctaButton": "AI System pe Upgrade Karein",

    "pricing.limitedOffer": "Mehdood Waqt ki Offer",
    "pricing.offerEnds": "Offer Jaldi Khatam Hone Wali Hai",
    "pricing.missOut": "Miss mat karein — Mehdood seats available hain!",
    "pricing.days": "Din",
    "pricing.hours": "Ghante",
    "pricing.min": "Min",
    "pricing.sec": "Sec",
    "pricing.basic": "Starter",
    "pricing.standard": "Standard",
    "pricing.premium": "Premium",
    "pricing.oneTime": "Ek dafa ki payment",
    "pricing.save": "Bachat",
    "pricing.starterNote": "Chhoti pharmacies ke liye behtareen",
    "pricing.standardNote": "Barhti hui pharmacies ke liye",
    "pricing.premiumNote": "Mukammal automated pharmacy business ke liye",
    "pricing.monthlyTitle": "Monthly Subscription Plans Dastiyab Hain",
    "pricing.monthlySub": "Domain, hosting, database, system updates, aur mukammal support — sab kuch ek fixed monthly fee mein.",
    "pricing.startMonthly": "Monthly Plans Ke Liye Rabta Karein",
    "pricing.investTitle": "Ek Dafa Ki Investment, Zindagi Bhar Ka Fayda",
    "pricing.investSub": "Ek dafa invest karein aur lifetime access, updates, aur support ka maza lein.",
    "pricing.recommended": "Recommended",
    "pricing.mostPopular": "Sab Se Mashhoor",
    "pricing.getStarted": "Shuru Karein",
    "pricing.upgradeStandard": "Standard pe Upgrade Karein",
    "pricing.getPremium": "Premium Abhi Lein",
    "pricing.everythingBasicPlus": "Starter mein sab kuch PLUS:",
    "pricing.everythingStandardPlus": "Standard mein sab kuch PLUS:",
    "pricing.aiPowered": "AI Powered",
    "pricing.hosting": "Hosting aur Domain",
    "pricing.hostingSub": "Hosting, Database aur Domain ki cost alag hai — Aap Adaa Karein",
    "pricing.yourBrand": "Apna Brand",
    "pricing.brandSub": "Jaise www.yourpharmacy.com",
    "pricing.fullSecurity": "Mukammal Security",
    "pricing.securitySub": "SSL, encryption aur daily backups",
    "pricing.f.pos": "POS Billing System",
    "pricing.f.inventory": "Smart Inventory Management",
    "pricing.f.expiry": "Expiry Alert System",
    "pricing.f.salesReports": "Sales Reports",
    "pricing.f.profitTracking": "Profit Tracking",
    "pricing.f.basicDashboard": "Basic Dashboard",
    "pricing.f.invoiceCustom": "Invoice Customization",
    "pricing.f.multiUserLimited": "Multi-User Access (Mehdood)",
    "pricing.f.dataBackup": "Data Backup System",
    "pricing.f.freeTrainingSetup": "Free Training aur Setup",
    "pricing.f.advancedPos": "Advanced POS",
    "pricing.f.fullInventory": "Mukammal Inventory Control",
    "pricing.f.advancedExpiry": "Advanced Expiry Alerts",
    "pricing.f.whatsappMarketing": "WhatsApp Marketing System",
    "pricing.f.staffMgmt": "Staff Management",
    "pricing.f.multiDevice": "Multi-Device Access",
    "pricing.f.advancedReports": "Advanced Reports",
    "pricing.f.profitAnalytics": "Profit Analytics",
    "pricing.f.customerHistory": "Customer History Tracking",
    "pricing.f.prioritySupport": "Priority Support",
    "pricing.f.aiSalesInsights": "AI Sales Insights",
    "pricing.f.aiMessageWriter": "AI Message Writer",
    "pricing.f.fullAutomation": "Mukammal Business Automation",
    "pricing.f.cloudHosting": "Cloud Hosting Setup",
    "pricing.f.advancedDashboard": "Advanced Dashboard",
    "pricing.f.unlimitedStaff": "Unlimited Staff Accounts",
    "pricing.f.advancedSecurity": "Advanced Security",
    "pricing.f.performanceTracking": "Performance Tracking",
    "pricing.f.smartRestock": "Smart Restock Suggestions",
    "pricing.f.vipSupport": "VIP Priority Support",

    "roi.title1": "AI ke Saath Tezi Se",
    "roi.title2": "Aagey Badhein",
    "roi.s1.label": "Waqt ki Bachat",
    "roi.s2.label": "Stock Loss Kam",
    "roi.s3.label": "Munafa Badhayein",
    "roi.s4.label": "Kaam Automate",

    "bonuses.badge": "Free Bonuses",
    "bonuses.title": "Software Se Zyada Milega",
    "bonuses.b1.title": "Free Mukammal Training",
    "bonuses.b1.desc": "Aap aur apke staff ke liye mukammal hands-on training. Har feature qadam ba qadam seekhein.",
    "bonuses.b2.title": "Free Lifetime Support",
    "bonuses.b2.desc": "WhatsApp ya call pe kisi bhi waqt expert help lein. Hum hamesha available hain.",
    "bonuses.b3.title": "Free Setup aur Installation",
    "bonuses.b3.desc": "Hamari team mukammal installation aur configuration karti hai. Aap ko koi technical skill nahi chahiye.",
    "bonuses.b4.title": "Free Data Migration",
    "bonuses.b4.desc": "Abuzar ya koi aur software use kar rahe hain? Hum apka purana data safely export kar ke import karte hain.",
    "bonuses.b5.title": "Free Updates",
    "bonuses.b5.desc": "Bina extra charges ke system upgrades. Latest technology ke saath modern aur competitive rahein.",
    "bonuses.b6.title": "Free Security Setup",
    "bonuses.b6.desc": "Backup system ke saath mukammal data protection. Apki pharmacy ka data safe aur secure rahe ga.",

    "testimonials.badge": "Asli Reviews",
    "testimonials.title1": "Hamare Customers Kya",
    "testimonials.title2": "Kehte Hain",
    "testimonials.subtitle": "Pakistan bhar ke pharmacy maalikon ka bharosa",

    "demo.title1": "Live Dekhein",
    "demo.title2": "Free Demo Book Karein",
    "demo.ctaButton": "WhatsApp pe Baat Karein",
    "demo.prefilled": 'Pehle se likha hua: "Hi, mujhe AI Pharmacy System ka demo chahiye."',

    "faq.title1": "Aksar Poochhe Jane Wale",
    "faq.title2": "Sawalaat",
    "faq.q1": "Mobile pe chalta hai?",
    "faq.a1": "Haan! Hamara system tamam mobile phones, tablets, aur desktop computers pe kaam karta hai. Kisi bhi browser se kahin se bhi access karein.",
    "faq.q2": "Training milegi?",
    "faq.a2": "Haan - bilkul free! Aap aur apke poore staff ke liye mukammal onboarding aur step-by-step training shamil hai.",
    "faq.q3": "Data secure hai?",
    "faq.a3": "Bilkul Secure. Industry-standard encryption, daily backups, aur sirf authorized access. Apka data hamare paas mehfooz hai.",
    "faq.q4": "Multiple devices pe chalega?",
    "faq.a4": "Haan! Standard aur Premium plans multi-device access support karte hain. Basic plan mein mehdood multi-user access shamil hai.",
    "faq.q5": "Kya purana data import ho sakta hai?",
    "faq.a5": "Bilkul! Agar aap Abuzar ya koi aur purana software use kar rahe hain, toh hum aap ka data safely export kar ke naye system mein import kar dete hain. Koi data loss nahi hota.",
    "faq.q6": "Internet na ho toh kya hoga?",
    "faq.a6": "System cloud-based hai, lekin basic billing offline bhi kaam karti hai. Jab internet wapas aaye ga, data automatically sync ho jaye ga. Premium plan mein full offline support shamil hai.",
    "faq.q7": "Kitne time mein setup ho jata hai?",
    "faq.a7": "Setup 24-48 hours mein mukammal ho jata hai. Hamari team full installation, configuration, aur training karti hai. Aap ko koi technical knowledge ki zaroorat nahi hai.",

    "showcase.badge": "Live Dekhein",
    "showcase.title": "Aapki Pharmacy Ka Sab Kuch, Ek System Mein",
    "showcase.subtitle": "Billing se AI insights tak — apni poori pharmacy ko ek powerful aur asaan platform se manage karein jo Pakistani pharmacies ke liye bana hai.",
    "showcase.cta": "Free Demo Book Karein",
    "showcase.check1": "Free Setup",
    "showcase.check2": "24/7 Support",

    "footer.smartPharmacy": "Apni Smart Pharmacy Aaj Shuru Karein.",
    "footer.chatWithUs": "Hum Se Baat Karein",
    "footer.quickLinks": "Quick Links",
    "footer.contact": "Rabta",
    "footer.whatsapp": "WhatsApp",
    "footer.copyright": "2026 Anas Tech Services. Tamam huqooq mehfooz hain.",

    "chatbot.title": "AI Pharmacy Assistant",
    "chatbot.status": "Online • Qeemat • Features • Mashwara",
    "chatbot.welcome": "Assalam o Alaikum! 👋 Main Anas Tech Services Pharmacy System ka AI assistant hoon. Mujh se qeemat, features, comparison, ya kuch bhi poochein!",
    "chatbot.askQuestions": "Sawaal Poochein?",
    "chatbot.askAI": "AI Se Poochein",
    "chatbot.placeholder": "Qeemat, features, mashwara ke baare mein poochein...",
    "chatbot.powered": "Powered by",
    "chatbot.q1": "Plans ki qeemat batayein",
    "chatbot.q2": "Kya features milte hain?",
    "chatbot.q3": "Manual se kyun behtar hai?",
    "chatbot.q4": "Kya mobile app hai?",
    "chatbot.q5": "Bonuses ke baare mein batayein",
    "chatbot.error": "Maafi, connection mein masla aa raha hai. Dobara koshish karein.",
    "chatbot.newChat": "Nayi Chat",
    "chatbot.minimize": "Chota Karein",
    "chatbot.fullscreen": "Bada Karein",
    "chatbot.close": "Band Karein",
  },

  ar: {
    "nav.subtitle": "نظام صيدلية ذكي",
    "nav.features": "المميزات",
    "nav.pricing": "الأسعار",
    "nav.demo": "فيديو تجريبي",
    "nav.faq": "الأسئلة الشائعة",
    "nav.contact": "اتصل بنا",
    "nav.bookDemo": "احجز عرض مجاني",

    "hero.badge": "نظام صيدلية سحابي بالذكاء الاصطناعي",
    "hero.title1": "أدر صيدليتك",
    "hero.title2": "بذكاء مع AI",
    "hero.subtitle": "نظام إدارة صيدلية سحابي متكامل مع نقاط البيع، المخزون الذكي، أتمتة واتساب ورؤى أعمال فورية",
    "hero.bookDemo": "احجز عرض مجاني على واتساب",
    "hero.watchDemo": "خطط الأسعار",
    "hero.freeTraining": "تدريب مجاني",
    "hero.freeSupport": "دعم مجاني مدى الحياة",
    "hero.worksOnMobile": "يعمل على الجوال والكمبيوتر",
    "hero.secureCloud": "نظام سحابي آمن",
    "hero.ourClients": "موثوق من الصيدليات",
    "hero.clientsPharmacies": "صيدليات",
    "hero.clientsCities": "مدن",
    "hero.clientsSatisfaction": "رضا",

    "pricing.limitedOffer": "عرض لفترة محدودة",
    "pricing.offerEnds": "العرض ينتهي قريباً",
    "pricing.missOut": "لا تفوت الفرصة — مقاعد محدودة متاحة!",
    "pricing.days": "أيام",
    "pricing.hours": "ساعات",
    "pricing.min": "دقائق",
    "pricing.sec": "ثواني",
    "pricing.basic": "المبتدئ",
    "pricing.standard": "القياسي",
    "pricing.premium": "المتميز",
    "pricing.oneTime": "دفعة واحدة",
    "pricing.save": "وفر",
    "pricing.starterNote": "مثالي للصيدليات الصغيرة",
    "pricing.standardNote": "الأفضل للصيدليات النامية",
    "pricing.premiumNote": "للصيدليات المؤتمتة بالكامل",
    "pricing.investTitle": "استثمار واحد، قيمة مدى الحياة",
    "pricing.investSub": "استثمر مرة واحدة واستمتع بوصول ودعم وتحديثات مدى الحياة",
    "pricing.mostPopular": "الأكثر شعبية",
    "pricing.getStarted": "ابدأ الآن",
    "pricing.upgradeStandard": "ترقية إلى القياسي",
    "pricing.getPremium": "احصل على المتميز",
    "pricing.everythingBasicPlus": "كل ما في المبتدئ بالإضافة إلى:",
    "pricing.everythingStandardPlus": "كل ما في القياسي بالإضافة إلى:",
    "pricing.aiPowered": "مدعوم بالذكاء الاصطناعي",

    "footer.smartPharmacy": "ابدأ صيدليتك الذكية اليوم",
    "footer.chatWithUs": "تحدث معنا",
    "footer.quickLinks": "روابط سريعة",
    "footer.contact": "اتصل بنا",
    "footer.whatsapp": "واتساب",
    "footer.copyright": "2026 أنس تك سيرفسز. جميع الحقوق محفوظة.",

    "chatbot.title": "مساعد الصيدلية الذكي",
    "chatbot.askQuestions": "اسأل سؤال؟",
    "chatbot.placeholder": "اسأل عن الأسعار والمميزات...",
  },
};
